apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user_profile_service.fullname" . }}
  labels:
    {{- include "user_profile_service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "user_profile_service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user_profile_service.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.commonEnvironment }}
            - name: {{ $key }}
              value: {{ $value | default "default_value" }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}


